
browser=chrome
baseUrl=https://katalon-demo-cura.herokuapp.com/
timeout=10
headless=false
valid.username=John Doe
valid.password=ThisIsNotAPassword
invalid.username=InvalidUser
invalid.password=InvalidPassword
